source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'rake'
gem 'haml'
gem 'sass'
gem 'heroku'
gem 'mysql2', '0.2.7'
gem 'rest-client'
gem 'jquery-rails', '>= 0.2.6'

group :development do
  gem 'capistrano'
end

group :test, :cucumber do
  gem 'rspec-rails'
  gem 'mocha'
  gem 'faker'
  gem 'ZenTest'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'cucumber'
  gem 'database_cleaner'
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'pickle'
end
