source 'http://rubygems.org'

gem 'rails', '3.0.3'
gem 'rake', '0.8.7'
gem 'haml'
gem 'pg'
gem 'authlogic'
gem 'paperclip', '2.3.3'
gem 'aws-s3', '0.6.2'
gem 'feedzirra', :git => 'git://github.com/pauldix/feedzirra.git'
gem 'loofah-activerecord', '1.0.0.beta.1'
gem 'loofah', '1.0.0.beta.1'
gem 'ri_cal', '0.8.7'
gem 'inherited_resources', '1.1.2'
gem 'icalendar', '1.1.5'

group :development do
  gem 'capistrano', '2.5.19'
end

group :test, :cucumber do
  gem 'rspec-rails', '2.4.1'
  gem 'mocha', '0.9.8'
  gem 'faker'
  gem 'ZenTest'
  gem 'autotest'
  gem 'autotest-rails'
  gem 'cucumber', '0.8.5'
  gem 'database_cleaner', '0.5.2'
  gem 'cucumber-rails', '0.3.2'
  gem 'capybara', '0.4.0'
  gem 'launchy'
  gem 'pickle', '0.4.4'
end
